#!/bin/sh
#
# makesrcdist - make a source distribution of RasterView.
#

if test $# != 1; then
	echo "Usage: makesrcdist version"
	exit 1
fi

version=$1

echo Creating tag for release...
git tag -m "Tag $version" v$version
git push origin v$version

echo Creating rasterview-$version.tar.gz...
git archive --format tar HEAD | gzip -v9 >~/Desktop/rasterview-$version.tar.gz
gpg --detach-sign ~/Desktop/rasterview-$version.tar.gz
